[每日任務]
enable = Y
command = -m src.main --debug --debug-action run-all
#command = -m src.main --debug run-all
timeout = 00:15:00


[每日簽到]
enable = Y
command = 
timeout = 00:02:00


[深淵]
enable = Y
command =  -m src.main --debug --debug-actions run-current-scene-task abyss
timeout = 00:05:00



[看廣告]
enable = Y
command = ads2/cli.py run --debug
timeout = 00:12:00

[王國金庫]
enable = Y
command = -m src.main --debug --debug-actions run-current-scene-task kingdom_vault
timeout = 00:05:00


[點金手]
enable = N
command = -m src.main --debug run-current-scene-task midas
timeout = 00:02:00


[勇者角逐廣告]
enable = N
command = ads2/cli.py run --debug
timeout = 00:03:00


[高階競技場]
enable = Y
command = -m src.main --debug --debug-actions run-current-scene-task advanced_arena
timeout = 00:05:00


[疾風呼喚]
enable = N
command = call_of_the_gale/scripts/auto_shoot.py
timeout = 00:20:00


[廣告每週遊戲]
enable = N
command = ads2/cli.py run --profile weekly_minigame --debug
timeout = 00:10:00


[廣告吉賽拉]
enable = N
command = ads2/cli.py run --debug
timeout = 00:02:00

[勇者角逐]
enable = N
command = -m src.main --debug --debug-actions run-current-scene-task hero_contest
timeout = 00:05:00


[廣告探寶鏟]
enable = N
command = ads2/cli.py run --debug
timeout = 00:12:00


[廣告時間沙漏]
enable = Y
command = ads2/cli.py run --debug
timeout = 00:12:00





