[settings]
#start_time = 08:00:30


[廣告探寶鏟]
enable = Y
command = ads2/cli.py run --debug

[廣告時間沙漏]
enable = N
command = ads2/cli.py run --debug

[每日任務]
enable = N
command = -m src.main --debug --debug-action run-all
#command = -m src.main --debug run-all


[深淵]
enable = N
command =  -m src.main --debug --debug-actions run-current-scene-task abyss



[看廣告]
enable = N
command = ads2/cli.py run --debug


[點金手]
enable = N
command = -m src.main --debug run-current-scene-task midas


[勇者角逐]
enable = N
command = -m src.main --debug --debug-actions run-current-scene-task hero_contest

[勇者角逐廣告]
enable = N
command = ads2/cli.py run --debug






[廣告每週遊戲]
enable = N
command = ads2/cli.py run --profile weekly_minigame --debug

[廣告吉賽拉]
enable = N
command = ads2/cli.py run --debug


[疾風呼喚]
enable = N
command = call_of_the_gale/scripts/auto_shoot.py






